name: Tourism Project Pipeline

on:
  push:
    branches:
      - main

jobs:
  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install --user -r tourism_project/requirements.txt

      - name: Run dataset registration
        run: |
          python tourism_project/model_building/data_register.py

  data-prep:
    runs-on: ubuntu-latest
    needs: register-dataset
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install --user -r tourism_project/requirements.txt

      - name: Run data prep
        run: |
          python tourism_project/model_building/prep.py

  model-training:
    runs-on: ubuntu-latest
    needs: data-prep
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install --user -r tourism_project/requirements.txt

      - name: Run training
        run: |
          python tourism_project/model_building/train.py

  deploy-hosting:
    runs-on: ubuntu-latest
    needs: model-training
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install --user -r tourism_project/requirements.txt

      - name: Deploy hosting
        run: |
          python tourism_project/hosting/hosting.py
