name: Tourism Package MLOps Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r tourism_project/requirements.txt

      - name: Set HF Token
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "HF_TOKEN=${HF_TOKEN}"

      - name: Train Model & Upload
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python tourism_project/model_building/train.py

      - name: Deploy App to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python tourism_project/hosting/hosting.py
